# Commented this, I don't know why I need promtail as a server :?
# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.zebra.town:3100/loki/api/v1/push

scrape_configs:
  - job_name: rails
    static_configs:
      - targets:
          - localhost
        labels:
          job: railsskeleton.com
          __path__: /var/log/rails/*.log
